export type Publication = {
  title: string;
  venue: string;
  venueShort: string;
  year: number;
  paperUrl?: string;
  pdfUrl?: string;
  codeUrl?: string;
};

export const publications: Publication[] = [
  {
    title: "Evaluating the Energy-Efficiency of the Code Generated by LLMs",
    venue: "Conference on Neural Information Processing Systems",
    venueShort: "FLLM 2025",
    year: 2025,
    paperUrl: "https://arxiv.org/abs/2505.20324",
    pdfUrl: "https://arxiv.org/pdf/2505.20324",
  },
  {
    title: "PlantHealthAI: An Integrated System for Plant Disease Detection, Severity Prediction with Knowledgebase Chatbot Support",
    venue: "International Conference on Smart Generation Computing, Communication and Networking",
    venueShort: "SMART GENCON 2023",
    year: 2023,
    paperUrl: "https://ieeexplore.ieee.org/document/10442890",
  },
  {
    title: "Robust and Scalable Network Monitoring System Using Apache Spark",
    venue: "International Conference on Recent Trends in Machine Learning, IoT, Smart Cities and Applications",
    venueShort: "ICMISC 2022",
    year: 2022,
    paperUrl: "https://link.springer.com/chapter/10.1007/978-981-19-6088-8_32",
  },
];
